dist: focal
language: java

jdk:
  - openjdk11

before_install:
  - nvm install --lts

cache:
  directories:
    - react/node_modules

script:
  - cd react
  - npm ci
  - npm run build
  - cd ..
  - cp -a react/build/. webapp/src/main/webapp
  - cd webapp
  - mvn clean install -DskipTests -Dgpg.skip=true
