name: Prepare The Runner

on:
  push:
  workflow_dispatch:

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME # env variable for username in deploy
        server-password: MAVEN_PASSWORD # env variable for token in deploy
        gpg-private-key: ${{ secrets.MVN_GPG_KEY }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

    - name: Cache Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: react/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('react/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules-

    - name: Clone ant-media-server-parent
      run: |
        git clone --depth=1 https://github.com/ant-media/ant-media-server-parent.git
        cd ant-media-server-parent
        mvn clean install -DskipTests -Dmaven.javadoc.skip=true -Dgpg.skip=true --quiet
        cd ..

    - name: Build React application
      env:
        NODE_OPTIONS: '--max-old-space-size=4096'
      run: |
        cd react
        sed -i "s#//placeholder for peerconnection_config#peerconnection_config:{\"iceServers\":[{\"urls\":\"turn:${{ secrets.STAGING_TURN_URL }}\",\"username\":\"${{ secrets.STAGING_TURN_USERNAME }}\",\"credential\":\"${{ secrets.STAGING_TURN_PASSWORD }}\"}],\"sdpSemantics\":\"unified-plan\"},#" src/pages/AntMedia.js
        npm install
        npm run build
        cd ..
        cp -a react/build/. webapp/src/main/webapp

    - name: Build Maven project
      run: |
        cd webapp
        mvn clean install -DskipTests -Dgpg.skip=true --quiet
        ls -alh
        ls -alh target/
        cd ..
        
    - name: Install Test Tool
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip iproute2 libva-drm2 libva-x11-2 libvdpau-dev ffmpeg
        curl -L "https://drive.usercontent.google.com/download?id=1Gp3LTFvG4arbXWFiGrQTPYw2CUEuKhf5&export=download&confirm=t" -o "webrtc-load-test-tool-2.9.1-SNAPSHOT.zip"
        unzip webrtc-load-test-tool-2.9.1-SNAPSHOT.zip
        mkdir ~/test
        mv webrtc-load-test ~/test
        
    - name: Install Selenium
      run: |
        wget https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.86/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo cp chromedriver-linux64/chromedriver /tmp
        ls -al /tmp
        pip3 install selenium==4.14
        pip3 install requests
        pip3 show selenium 
        pip3 install psutil

  